name: CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build step (simulado)
        run: echo "Building project..."

      - name: Run deployment step (simulado)
        run: echo "Deploy realizado com sucesso 🚀"